spring:
  datasource:
    url: jdbc:mysql://192.168.0.10:3306/powerdatabase?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20

mybatis:
  type-aliases-package: com.powernote.skeleton.mapper  # model 객체
  mapper-locations: classpath:mapper/**/*.xml