spring:
  datasource:
    url: jdbc:oracle:thin:@ATPDBNAME_high?TNS_ADMIN=/oracle/oracle_atp/Wallet_ATPDBNAME/
    username: ADMIN
    password: xxxxxx
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      max-lifetime: 240000
      pool-name: oraPool

  mvc:
    static-path-pattern: /**

  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
      add-mappings: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false

mybatis:
  type-aliases-package: com.powernote.skeleton.mapper  #

